blank_issues_enabled: false
contact_links:
  - name: 🆘 Code of Conduct Reports
    url: https://github.com/AlejandroSuero/freeze-code.nvim/blob/main/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct
    about: Please use the contact information in Code of Conduct as issues created here are public
