name: codespell

on: [pull_request]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install codespell
        run: pip install codespell
      - name: Use codespell
        run: make spell
