name: test

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rev: [nightly, v0.9.0, stable]

    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Run tests with NeoVim
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test-nvim

      - uses: actions/checkout@v4

      - name: Install LuaJIT
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Run test with vusted
        shell: bash
        run: |
          luarocks install vusted
          nvim --version
          make test
